-- сбрасываем счетчик
SELECT setval('currencies_id_seq', 1, false);
SELECT setval('balance_types_id_seq', 1, false);
SELECT setval('transaction_types_id_seq', 1, false);
SELECT setval('balances_id_seq', 1, false);
SELECT setval('transactions_id_seq', 1, false);
-- end

INSERT INTO currencies (name) VALUES
    ('Поинты'),
    ('Бонусы'), ('RUB'), ('USD'), ('STARS'), ('EUR') RETURNING id, name;
    
INSERT INTO balance_types (name) VALUES
    ('Основной счет'),
    ('Бонусный счет') RETURNING id, name;
    
INSERT INTO transaction_types (name) VALUES
    ('Пополнение'),
    ('Списание') RETURNING id, name;

-- 1 - основной счет; 2 - бонусный счет
INSERT INTO balances (balances_type_id) VALUES
    (1),(2),(1),(2),(1),(2),(1),(2),(1),(2);
 
-- транзакции на пополнения счета lastval()
INSERT INTO transactions (quantity, balance_id, transaction_type_id, currency_id, created_at, updated_at) VALUES
	-- пополнение основного счета
    (floor(random() * 1000), 1, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 3, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 5, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 7, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 9, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365),
    (floor(random() * 1000), 1, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 3, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 5, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 7, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365), (floor(random() * 1000), 9, 1, 1, CURRENT_DATE-365, CURRENT_DATE-365),
    (floor(random() * 1000), 1, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 1, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 1, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 1, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    
	-- пополнение бонусного счета
	(floor(random() * 1000), 2, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
	(floor(random() * 1000), 2, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
	(floor(random() * 1000), 2, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
	(floor(random() * 1000), 2, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
	(floor(random() * 1000), 2, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 1, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    
--     списание с основного счета
    (floor(random() * 1000), 1, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 1, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 1, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 1, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 1, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 3, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 5, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 7, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 9, 2, 1, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    
--  списание с бонусного счета
    (floor(random() * 1000), 2, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 2, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 2, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 2, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)),
    (floor(random() * 1000), 2, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 4, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 6, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 8, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval)), (floor(random() * 1000), 10, 2, 2, date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval), date_add(CURRENT_DATE - 365, FORMAT('%s days', lastval() + 1)::interval))
    
    RETURNING id, quantity, balance_id, transaction_type_id, currency_id, created_at, updated_at;

-- Выбрать все транзакции с суммой больше 100 (слишком много выводится и я сделал больше 950)
select * from transactions WHERE quantity > 950;

-- Выбрать все нулевые транзакции за прошедшую неделю
select * from transactions 
WHERE (created_at >= date_trunc('week', CURRENT_TIMESTAMP - interval '1 week') and
      created_at < date_trunc('week', CURRENT_TIMESTAMP) and quantity = 0);

-- вывести первые пять наименований валют 
select * from currencies ORDER BY id ASC
LIMIT 5;